//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Mumble.proto
using System;

namespace MumbleProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Version")]
  public partial class Version : global::ProtoBuf.IExtensible
  {
    public Version() {}
    
    private uint _version = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _release = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"release", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string release
    {
      get { return _release; }
      set { _release = value; }
    }
    private string _os = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"os", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string os
    {
      get { return _os; }
      set { _os = value; }
    }
    private string _os_version = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"os_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string os_version
    {
      get { return _os_version; }
      set { _os_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UDPTunnel")]
  public partial class UDPTunnel : global::ProtoBuf.IExtensible
  {
    public UDPTunnel() {}
    
    private byte[] _packet;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"packet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] packet
    {
      get { return _packet; }
      set { _packet = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Authenticate")]
  public partial class Authenticate : global::ProtoBuf.IExtensible
  {
    public Authenticate() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _tokens = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"tokens", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> tokens
    {
      get { return _tokens; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _celt_versions = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"celt_versions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> celt_versions
    {
      get { return _celt_versions; }
    }
  
    private bool _opus = (bool)false;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"opus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool opus
    {
      get { return _opus; }
      set { _opus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Ping")]
  public partial class Ping : global::ProtoBuf.IExtensible
  {
    public Ping() {}
    
    private ulong _timestamp = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private uint _good = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"good", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint good
    {
      get { return _good; }
      set { _good = value; }
    }
    private uint _late = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"late", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint late
    {
      get { return _late; }
      set { _late = value; }
    }
    private uint _lost = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lost
    {
      get { return _lost; }
      set { _lost = value; }
    }
    private uint _resync = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"resync", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint resync
    {
      get { return _resync; }
      set { _resync = value; }
    }
    private uint _udp_packets = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"udp_packets", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint udp_packets
    {
      get { return _udp_packets; }
      set { _udp_packets = value; }
    }
    private uint _tcp_packets = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"tcp_packets", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tcp_packets
    {
      get { return _tcp_packets; }
      set { _tcp_packets = value; }
    }
    private float _udp_ping_avg = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"udp_ping_avg", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float udp_ping_avg
    {
      get { return _udp_ping_avg; }
      set { _udp_ping_avg = value; }
    }
    private float _udp_ping_var = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"udp_ping_var", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float udp_ping_var
    {
      get { return _udp_ping_var; }
      set { _udp_ping_var = value; }
    }
    private float _tcp_ping_avg = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"tcp_ping_avg", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float tcp_ping_avg
    {
      get { return _tcp_ping_avg; }
      set { _tcp_ping_avg = value; }
    }
    private float _tcp_ping_var = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"tcp_ping_var", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float tcp_ping_var
    {
      get { return _tcp_ping_var; }
      set { _tcp_ping_var = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Reject")]
  public partial class Reject : global::ProtoBuf.IExtensible
  {
    public Reject() {}
    
    private MumbleProto.Reject.RejectType _type = MumbleProto.Reject.RejectType.None;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MumbleProto.Reject.RejectType.None)]
    public MumbleProto.Reject.RejectType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _reason = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RejectType")]
    public enum RejectType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"None", Value=0)]
      None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WrongVersion", Value=1)]
      WrongVersion = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InvalidUsername", Value=2)]
      InvalidUsername = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WrongUserPW", Value=3)]
      WrongUserPW = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WrongServerPW", Value=4)]
      WrongServerPW = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UsernameInUse", Value=5)]
      UsernameInUse = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerFull", Value=6)]
      ServerFull = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoCertificate", Value=7)]
      NoCertificate = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerConfig")]
  public partial class ServerConfig : global::ProtoBuf.IExtensible
  {
    public ServerConfig() {}
    
    private uint _max_bandwidth = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"max_bandwidth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_bandwidth
    {
      get { return _max_bandwidth; }
      set { _max_bandwidth = value; }
    }
    private string _welcome_text = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"welcome_text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string welcome_text
    {
      get { return _welcome_text; }
      set { _welcome_text = value; }
    }
    private bool _allow_html = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"allow_html", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool allow_html
    {
      get { return _allow_html; }
      set { _allow_html = value; }
    }
    private uint _message_length = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"message_length", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint message_length
    {
      get { return _message_length; }
      set { _message_length = value; }
    }
    private uint _image_message_length = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"image_message_length", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint image_message_length
    {
      get { return _image_message_length; }
      set { _image_message_length = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerSync")]
  public partial class ServerSync : global::ProtoBuf.IExtensible
  {
    public ServerSync() {}
    
    private uint _session = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint session
    {
      get { return _session; }
      set { _session = value; }
    }
    private uint _max_bandwidth = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_bandwidth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_bandwidth
    {
      get { return _max_bandwidth; }
      set { _max_bandwidth = value; }
    }
    private string _welcome_text = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"welcome_text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string welcome_text
    {
      get { return _welcome_text; }
      set { _welcome_text = value; }
    }
    private ulong _permissions = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"permissions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong permissions
    {
      get { return _permissions; }
      set { _permissions = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChannelRemove")]
  public partial class ChannelRemove : global::ProtoBuf.IExtensible
  {
    public ChannelRemove() {}
    
    private uint _channel_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChannelState")]
  public partial class ChannelState : global::ProtoBuf.IExtensible
  {
    public ChannelState() {}
    
    private uint _channel_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private uint _parent = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"parent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint parent
    {
      get { return _parent; }
      set { _parent = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _links = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"links", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> links
    {
      get { return _links; }
    }
  
    private string _description = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _links_add = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"links_add", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> links_add
    {
      get { return _links_add; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _links_remove = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"links_remove", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> links_remove
    {
      get { return _links_remove; }
    }
  
    private bool _temporary = (bool)false;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"temporary", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool temporary
    {
      get { return _temporary; }
      set { _temporary = value; }
    }
    private int _position = (int)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private byte[] _description_hash = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"description_hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] description_hash
    {
      get { return _description_hash; }
      set { _description_hash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserRemove")]
  public partial class UserRemove : global::ProtoBuf.IExtensible
  {
    public UserRemove() {}
    
    private uint _session;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint session
    {
      get { return _session; }
      set { _session = value; }
    }
    private uint _actor = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"actor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint actor
    {
      get { return _actor; }
      set { _actor = value; }
    }
    private string _reason = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private bool _ban = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ban", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ban
    {
      get { return _ban; }
      set { _ban = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserState")]
  public partial class UserState : global::ProtoBuf.IExtensible
  {
    public UserState() {}
    
    private uint _session = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint session
    {
      get { return _session; }
      set { _session = value; }
    }
    private uint _actor = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"actor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint actor
    {
      get { return _actor; }
      set { _actor = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _user_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private uint _channel_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private bool _mute = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool mute
    {
      get { return _mute; }
      set { _mute = value; }
    }
    private bool _deaf = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"deaf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool deaf
    {
      get { return _deaf; }
      set { _deaf = value; }
    }
    private bool _suppress = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"suppress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool suppress
    {
      get { return _suppress; }
      set { _suppress = value; }
    }
    private bool _self_mute = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"self_mute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool self_mute
    {
      get { return _self_mute; }
      set { _self_mute = value; }
    }
    private bool _self_deaf = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"self_deaf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool self_deaf
    {
      get { return _self_deaf; }
      set { _self_deaf = value; }
    }
    private byte[] _texture = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"texture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] texture
    {
      get { return _texture; }
      set { _texture = value; }
    }
    private byte[] _plugin_context = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"plugin_context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] plugin_context
    {
      get { return _plugin_context; }
      set { _plugin_context = value; }
    }
    private string _plugin_identity = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"plugin_identity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string plugin_identity
    {
      get { return _plugin_identity; }
      set { _plugin_identity = value; }
    }
    private string _comment = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"comment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string comment
    {
      get { return _comment; }
      set { _comment = value; }
    }
    private string _cert_hash = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"cert_hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cert_hash
    {
      get { return _cert_hash; }
      set { _cert_hash = value; }
    }
    private byte[] _comment_hash = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"comment_hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] comment_hash
    {
      get { return _comment_hash; }
      set { _comment_hash = value; }
    }
    private byte[] _texture_hash = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"texture_hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] texture_hash
    {
      get { return _texture_hash; }
      set { _texture_hash = value; }
    }
    private bool _priority_speaker = default(bool);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"priority_speaker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool priority_speaker
    {
      get { return _priority_speaker; }
      set { _priority_speaker = value; }
    }
    private bool _recording = default(bool);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"recording", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool recording
    {
      get { return _recording; }
      set { _recording = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BanList")]
  public partial class BanList : global::ProtoBuf.IExtensible
  {
    public BanList() {}
    
    private readonly global::System.Collections.Generic.List<MumbleProto.BanList.BanEntry> _bans = new global::System.Collections.Generic.List<MumbleProto.BanList.BanEntry>();
    [global::ProtoBuf.ProtoMember(1, Name=@"bans", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MumbleProto.BanList.BanEntry> bans
    {
      get { return _bans; }
    }
  
    private bool _query = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"query", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool query
    {
      get { return _query; }
      set { _query = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BanEntry")]
  public partial class BanEntry : global::ProtoBuf.IExtensible
  {
    public BanEntry() {}
    
    private byte[] _address;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] address
    {
      get { return _address; }
      set { _address = value; }
    }
    private uint _mask;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mask
    {
      get { return _mask; }
      set { _mask = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _cert_hash = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cert_hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cert_hash
    {
      get { return _cert_hash; }
      set { _cert_hash = value; }
    }
    private string _reason = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private string _start = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string start
    {
      get { return _start; }
      set { _start = value; }
    }
    private uint _duration = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TextMessage")]
  public partial class TextMessage : global::ProtoBuf.IExtensible
  {
    public TextMessage() {}
    
    private uint _actor = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"actor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint actor
    {
      get { return _actor; }
      set { _actor = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _session = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> session
    {
      get { return _session; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _channel_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> channel_id
    {
      get { return _channel_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _tree_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"tree_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> tree_id
    {
      get { return _tree_id; }
    }
  
    private string _message;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PermissionDenied")]
  public partial class PermissionDenied : global::ProtoBuf.IExtensible
  {
    public PermissionDenied() {}
    
    private uint _permission = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"permission", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint permission
    {
      get { return _permission; }
      set { _permission = value; }
    }
    private uint _channel_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private uint _session = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint session
    {
      get { return _session; }
      set { _session = value; }
    }
    private string _reason = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private MumbleProto.PermissionDenied.DenyType _type = MumbleProto.PermissionDenied.DenyType.Text;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MumbleProto.PermissionDenied.DenyType.Text)]
    public MumbleProto.PermissionDenied.DenyType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"DenyType")]
    public enum DenyType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Text", Value=0)]
      Text = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Permission", Value=1)]
      Permission = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SuperUser", Value=2)]
      SuperUser = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChannelName", Value=3)]
      ChannelName = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TextTooLong", Value=4)]
      TextTooLong = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"H9K", Value=5)]
      H9K = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TemporaryChannel", Value=6)]
      TemporaryChannel = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MissingCertificate", Value=7)]
      MissingCertificate = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserName", Value=8)]
      UserName = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChannelFull", Value=9)]
      ChannelFull = 9
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ACL")]
  public partial class ACL : global::ProtoBuf.IExtensible
  {
    public ACL() {}
    
    private uint _channel_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private bool _inherit_acls = (bool)true;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"inherit_acls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool inherit_acls
    {
      get { return _inherit_acls; }
      set { _inherit_acls = value; }
    }
    private readonly global::System.Collections.Generic.List<MumbleProto.ACL.ChanGroup> _groups = new global::System.Collections.Generic.List<MumbleProto.ACL.ChanGroup>();
    [global::ProtoBuf.ProtoMember(3, Name=@"groups", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MumbleProto.ACL.ChanGroup> groups
    {
      get { return _groups; }
    }
  
    private readonly global::System.Collections.Generic.List<MumbleProto.ACL.ChanACL> _acls = new global::System.Collections.Generic.List<MumbleProto.ACL.ChanACL>();
    [global::ProtoBuf.ProtoMember(4, Name=@"acls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MumbleProto.ACL.ChanACL> acls
    {
      get { return _acls; }
    }
  
    private bool _query = (bool)false;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"query", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool query
    {
      get { return _query; }
      set { _query = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChanGroup")]
  public partial class ChanGroup : global::ProtoBuf.IExtensible
  {
    public ChanGroup() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private bool _inherited = (bool)true;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"inherited", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool inherited
    {
      get { return _inherited; }
      set { _inherited = value; }
    }
    private bool _inherit = (bool)true;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"inherit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool inherit
    {
      get { return _inherit; }
      set { _inherit = value; }
    }
    private bool _inheritable = (bool)true;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"inheritable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool inheritable
    {
      get { return _inheritable; }
      set { _inheritable = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _add = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"add", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> add
    {
      get { return _add; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _remove = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"remove", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> remove
    {
      get { return _remove; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _inherited_members = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"inherited_members", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> inherited_members
    {
      get { return _inherited_members; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChanACL")]
  public partial class ChanACL : global::ProtoBuf.IExtensible
  {
    public ChanACL() {}
    
    private bool _apply_here = (bool)true;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"apply_here", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool apply_here
    {
      get { return _apply_here; }
      set { _apply_here = value; }
    }
    private bool _apply_subs = (bool)true;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"apply_subs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool apply_subs
    {
      get { return _apply_subs; }
      set { _apply_subs = value; }
    }
    private bool _inherited = (bool)true;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"inherited", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool inherited
    {
      get { return _inherited; }
      set { _inherited = value; }
    }
    private uint _user_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _group = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string group
    {
      get { return _group; }
      set { _group = value; }
    }
    private uint _grant = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"grant", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint grant
    {
      get { return _grant; }
      set { _grant = value; }
    }
    private uint _deny = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"deny", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint deny
    {
      get { return _deny; }
      set { _deny = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryUsers")]
  public partial class QueryUsers : global::ProtoBuf.IExtensible
  {
    public QueryUsers() {}
    
    private readonly global::System.Collections.Generic.List<uint> _ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> ids
    {
      get { return _ids; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _names = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"names", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> names
    {
      get { return _names; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CryptSetup")]
  public partial class CryptSetup : global::ProtoBuf.IExtensible
  {
    public CryptSetup() {}
    
    private byte[] _key = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] key
    {
      get { return _key; }
      set { _key = value; }
    }
    private byte[] _client_nonce = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"client_nonce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] client_nonce
    {
      get { return _client_nonce; }
      set { _client_nonce = value; }
    }
    private byte[] _server_nonce = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"server_nonce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] server_nonce
    {
      get { return _server_nonce; }
      set { _server_nonce = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ContextActionModify")]
  public partial class ContextActionModify : global::ProtoBuf.IExtensible
  {
    public ContextActionModify() {}
    
    private string _action;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string action
    {
      get { return _action; }
      set { _action = value; }
    }
    private string _text = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private uint _context = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint context
    {
      get { return _context; }
      set { _context = value; }
    }
    private MumbleProto.ContextActionModify.Operation _operation = MumbleProto.ContextActionModify.Operation.Add;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MumbleProto.ContextActionModify.Operation.Add)]
    public MumbleProto.ContextActionModify.Operation operation
    {
      get { return _operation; }
      set { _operation = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Context")]
    public enum Context
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Server", Value=1)]
      Server = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Channel", Value=2)]
      Channel = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"User", Value=4)]
      User = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Operation")]
    public enum Operation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Add", Value=0)]
      Add = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Remove", Value=1)]
      Remove = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ContextAction")]
  public partial class ContextAction : global::ProtoBuf.IExtensible
  {
    public ContextAction() {}
    
    private uint _session = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint session
    {
      get { return _session; }
      set { _session = value; }
    }
    private uint _channel_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private string _action;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string action
    {
      get { return _action; }
      set { _action = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserList")]
  public partial class UserList : global::ProtoBuf.IExtensible
  {
    public UserList() {}
    
    private readonly global::System.Collections.Generic.List<MumbleProto.UserList.User> _users = new global::System.Collections.Generic.List<MumbleProto.UserList.User>();
    [global::ProtoBuf.ProtoMember(1, Name=@"users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MumbleProto.UserList.User> users
    {
      get { return _users; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User")]
  public partial class User : global::ProtoBuf.IExtensible
  {
    public User() {}
    
    private uint _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VoiceTarget")]
  public partial class VoiceTarget : global::ProtoBuf.IExtensible
  {
    public VoiceTarget() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<MumbleProto.VoiceTarget.Target> _targets = new global::System.Collections.Generic.List<MumbleProto.VoiceTarget.Target>();
    [global::ProtoBuf.ProtoMember(2, Name=@"targets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MumbleProto.VoiceTarget.Target> targets
    {
      get { return _targets; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Target")]
  public partial class Target : global::ProtoBuf.IExtensible
  {
    public Target() {}
    
    private readonly global::System.Collections.Generic.List<uint> _session = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> session
    {
      get { return _session; }
    }
  
    private uint _channel_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private string _group = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string group
    {
      get { return _group; }
      set { _group = value; }
    }
    private bool _links = (bool)false;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"links", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool links
    {
      get { return _links; }
      set { _links = value; }
    }
    private bool _children = (bool)false;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"children", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool children
    {
      get { return _children; }
      set { _children = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PermissionQuery")]
  public partial class PermissionQuery : global::ProtoBuf.IExtensible
  {
    public PermissionQuery() {}
    
    private uint _channel_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"channel_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint channel_id
    {
      get { return _channel_id; }
      set { _channel_id = value; }
    }
    private uint _permissions = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"permissions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint permissions
    {
      get { return _permissions; }
      set { _permissions = value; }
    }
    private bool _flush = (bool)false;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"flush", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool flush
    {
      get { return _flush; }
      set { _flush = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CodecVersion")]
  public partial class CodecVersion : global::ProtoBuf.IExtensible
  {
    public CodecVersion() {}
    
    private int _alpha;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"alpha", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int alpha
    {
      get { return _alpha; }
      set { _alpha = value; }
    }
    private int _beta;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"beta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int beta
    {
      get { return _beta; }
      set { _beta = value; }
    }
    private bool _prefer_alpha;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"prefer_alpha", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool prefer_alpha
    {
      get { return _prefer_alpha; }
      set { _prefer_alpha = value; }
    }
    private bool _opus = (bool)false;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"opus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool opus
    {
      get { return _opus; }
      set { _opus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserStats")]
  public partial class UserStats : global::ProtoBuf.IExtensible
  {
    public UserStats() {}
    
    private uint _session = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint session
    {
      get { return _session; }
      set { _session = value; }
    }
    private bool _stats_only = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stats_only", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool stats_only
    {
      get { return _stats_only; }
      set { _stats_only = value; }
    }
    private readonly global::System.Collections.Generic.List<byte[]> _certificates = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(3, Name=@"certificates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> certificates
    {
      get { return _certificates; }
    }
  
    private MumbleProto.UserStats.Stats _from_client = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"from_client", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MumbleProto.UserStats.Stats from_client
    {
      get { return _from_client; }
      set { _from_client = value; }
    }
    private MumbleProto.UserStats.Stats _from_server = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"from_server", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MumbleProto.UserStats.Stats from_server
    {
      get { return _from_server; }
      set { _from_server = value; }
    }
    private uint _udp_packets = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"udp_packets", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint udp_packets
    {
      get { return _udp_packets; }
      set { _udp_packets = value; }
    }
    private uint _tcp_packets = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"tcp_packets", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tcp_packets
    {
      get { return _tcp_packets; }
      set { _tcp_packets = value; }
    }
    private float _udp_ping_avg = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"udp_ping_avg", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float udp_ping_avg
    {
      get { return _udp_ping_avg; }
      set { _udp_ping_avg = value; }
    }
    private float _udp_ping_var = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"udp_ping_var", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float udp_ping_var
    {
      get { return _udp_ping_var; }
      set { _udp_ping_var = value; }
    }
    private float _tcp_ping_avg = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"tcp_ping_avg", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float tcp_ping_avg
    {
      get { return _tcp_ping_avg; }
      set { _tcp_ping_avg = value; }
    }
    private float _tcp_ping_var = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"tcp_ping_var", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float tcp_ping_var
    {
      get { return _tcp_ping_var; }
      set { _tcp_ping_var = value; }
    }
    private MumbleProto.Version _version = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MumbleProto.Version version
    {
      get { return _version; }
      set { _version = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _celt_versions = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"celt_versions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> celt_versions
    {
      get { return _celt_versions; }
    }
  
    private byte[] _address = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] address
    {
      get { return _address; }
      set { _address = value; }
    }
    private uint _bandwidth = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"bandwidth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bandwidth
    {
      get { return _bandwidth; }
      set { _bandwidth = value; }
    }
    private uint _onlinesecs = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"onlinesecs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint onlinesecs
    {
      get { return _onlinesecs; }
      set { _onlinesecs = value; }
    }
    private uint _idlesecs = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"idlesecs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint idlesecs
    {
      get { return _idlesecs; }
      set { _idlesecs = value; }
    }
    private bool _strong_certificate = (bool)false;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"strong_certificate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool strong_certificate
    {
      get { return _strong_certificate; }
      set { _strong_certificate = value; }
    }
    private bool _opus = (bool)false;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"opus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool opus
    {
      get { return _opus; }
      set { _opus = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stats")]
  public partial class Stats : global::ProtoBuf.IExtensible
  {
    public Stats() {}
    
    private uint _good = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"good", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint good
    {
      get { return _good; }
      set { _good = value; }
    }
    private uint _late = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"late", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint late
    {
      get { return _late; }
      set { _late = value; }
    }
    private uint _lost = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lost
    {
      get { return _lost; }
      set { _lost = value; }
    }
    private uint _resync = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"resync", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint resync
    {
      get { return _resync; }
      set { _resync = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SuggestConfig")]
  public partial class SuggestConfig : global::ProtoBuf.IExtensible
  {
    public SuggestConfig() {}
    
    private uint _version = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint version
    {
      get { return _version; }
      set { _version = value; }
    }
    private bool _positional = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"positional", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool positional
    {
      get { return _positional; }
      set { _positional = value; }
    }
    private bool _push_to_talk = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"push_to_talk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool push_to_talk
    {
      get { return _push_to_talk; }
      set { _push_to_talk = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestBlob")]
  public partial class RequestBlob : global::ProtoBuf.IExtensible
  {
    public RequestBlob() {}
    
    private readonly global::System.Collections.Generic.List<uint> _session_texture = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"session_texture", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> session_texture
    {
      get { return _session_texture; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _session_comment = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"session_comment", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> session_comment
    {
      get { return _session_comment; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _channel_description = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"channel_description", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> channel_description
    {
      get { return _channel_description; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}